### PR TITLE
Passwords, Windows, and Error bubbling, oh my

### PR DESCRIPTION
**Pull request by rathboma**
FYI - Love this library, by far the simplest and most obvious implementation of a SSH tunnel library. Thank you for making it!

Included in this PR:

- Connection errors properly reject the promise
- The SSH agent detection now supports Windows and Putty
- The SSH connection now supports password auth
- Users can provide a custom agent socket

### CODE REVIEW

**Comment by rathboma** [comment]
I think I'm done with this. Please let me know if you have any feedback or changes. Would love to be able to include a new version of this lib properly in my app!

**Comment by Junkern** [comment]
Oh, very nice! Could you update the README with the two new connection options? I also thought about tests for the windows agent detection, but I assume that you are using this feature already, so it must be working ;)

**Comment by rathboma** [comment]
Sure! Actually haven't tested the windows agent yet, but it is according to the docs. It should be tested in the next couple of days

**Comment by rathboma** [comment]
So I have confirmed a few things:

- ssh agent pass-through works (haven't tested pageant on windows yet)
- connection.connect() can actually throw an exception if you have an encrypted private key and no password is provided, solved that
- If you use an agent, you shouldn't read the private key. If the key is encrypted it throws an error, rather than using the agent

**Comment by rathboma** [comment]
Honestly, it probably shouldn't read `id_rsa` by default, but I've maintained that behavior for backwards compatibility, but added an override

**Comment by Junkern** [comment]
Awesome, thank you so much for the contribution! Your PR will land as `0.7.0` in a bit ;)

**Comment by rathboma** [comment]
Thanks! Also - confirmed Pageant is working :-)

**Pull request merged**
